Add missing labels in VS ontology
edmcouncil/auto pull request #120
Opened 2023-01-03 18:38 UTC by kwlodarczyk0

Signed-off-by: kwlodarczyk0 <wlodarczyk.krystian00@gmail.com>

Fixes: #118

2023-01-09 09:07 UTC, mereolog requested changes

2023-01-09 09:07 UTC, mereolog commented on VS/VehicleSignals.rdf
> +		<rdfs:label xml:lang="en">Catalyst Temperature Sensor</rdfs:label>
Note that https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#naming-and-labeling-conventions requires all labels be lower case.

2023-01-09 09:07 UTC, mereolog commented on VS/VehicleSignals.rdf
> +		<rdfs:label xml:lang="en">Coolant Temperature Sensor</rdfs:label>
Note that https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#naming-and-labeling-conventions requires all labels be lower case.

2023-01-09 09:07 UTC, mereolog commented on VS/VehicleSignals.rdf
> +		<rdfs:label xml:lang="en">Crankshaft Position Sensor</rdfs:label>
Note that https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#naming-and-labeling-conventions requires all labels be lower case.

2023-01-09 09:07 UTC, mereolog commented on VS/VehicleSignals.rdf
> +		<rdfs:label xml:lang="en">Cushion Position Sensor</rdfs:label>
Note that https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#naming-and-labeling-conventions requires all labels be lower case.

2023-01-10 12:35 UTC, mskulim approved these changes

2023-01-10 16:12 UTC, merged