Multiple labels in MiddleOntology and VehicleCore and missing label in TrafficEnvironment
edmcouncil/auto pull request #127
Opened 2023-01-05 22:05 UTC by kord4s

Resource [Angle](https://spec.edmcouncil.org/auto/ontology/VS/VehicleSignals/SteeringWheelAngle) doesn't have a label

> Every class, property, and individual must have a label, at a minimum, with additional annotations as described below. It should be the natural language (American English) representation of that entity, space-separated, including the language tag for English.

Resource [Location](https://spec.edmcouncil.org/auto/ontology/MO/MiddleOntology/Location) has multiple labels. 
> FIBO enforces both unique labels and unique names conventions, even across namespaces. There is content in the provisional and informative ontologies that does not adhere to these policies, but for any released ontology, we require unique naming and unique labeling.

Resource [bodyStyle](https://spec.edmcouncil.org/auto/ontology/VC/VehicleCore/bodyStyle) has multiple labels.
> FIBO enforces both unique labels and unique names conventions, even across namespaces. There is content in the provisional and informative ontologies that does not adhere to these policies, but for any released ontology, we require unique naming and unique labeling.

2023-01-09 08:12 UTC, mereolog commented
@kord4s note that the DCO test failed - remember to use -sm option in all commits.

2023-01-09 09:11 UTC, mereolog requested changes

2023-01-09 09:11 UTC, mereolog commented on DE/TrafficEnvironment.rdf
> +		<rdfs:label>Angle</rdfs:label>
Note that https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#naming-and-labeling-conventions requires all labels be lower case.

2023-01-09 09:11 UTC, mereolog commented on MO/MiddleOntology.rdf
> +		<rdfs:label xml:lang="en">Location</rdfs:label>
Note that https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#naming-and-labeling-conventions requires all labels be lower case.

2023-01-09 09:11 UTC, mereolog commented on VC/VehicleCore.rdf
> -		<rdfs:label xml:lang="en">body type</rdfs:label>
It would be better to change the property type than just to delete the label.

2023-01-10 14:33 UTC, kord4s reviewed
changes have been made

2023-01-10 14:33 UTC, closed without merging