added labels to multiple resources in VS ontology (WIP)
edmcouncil/auto pull request #129
Opened 2023-01-06 04:31 UTC by Bardawulf

Signed-off-by: Bardawulf <kanarek365@gmail.com>

Fixes: #126

2023-01-09 08:13 UTC, mereolog commented
@Bardawulf is this ready for review?
If so, could you remove the WIP suffix from the name of this pull request?

2023-01-09 09:12 UTC, mereolog requested changes

2023-01-09 09:12 UTC, mereolog commented on VS/VehicleSignals.rdf
> +		<rdfs:label xml:lang="en">Intake air temperature sensor</rdfs:label>
Note that https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#naming-and-labeling-conventions requires all labels be lower case.

2023-01-09 09:12 UTC, mereolog commented on VS/VehicleSignals.rdf
> +		<rdfs:label xml:lang="en">Is backup light on</rdfs:label>
Note that https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#naming-and-labeling-conventions requires all labels be lower case.

2023-01-09 09:12 UTC, mereolog commented on VS/VehicleSignals.rdf
> +		<rdfs:label xml:lang="en">Left indicator light</rdfs:label>
Note that https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#naming-and-labeling-conventions requires all labels be lower case.

2023-01-09 09:12 UTC, mereolog commented on VS/VehicleSignals.rdf
> +		<rdfs:label xml:lang="en">Lidar</rdfs:label>
Note that https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#naming-and-labeling-conventions requires all labels be lower case.

2023-01-09 09:12 UTC, mereolog commented on VS/VehicleSignals.rdf
> +		<rdfs:label xml:lang="en">Lumbar pressure sensor</rdfs:label>
Note that https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#naming-and-labeling-conventions requires all labels be lower case.

2023-01-09 09:12 UTC, mereolog commented on VS/VehicleSignals.rdf
> +		<rdfs:label xml:lang="en">Right indicator light</rdfs:label>
Note that https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#naming-and-labeling-conventions requires all labels be lower case.

2023-01-09 09:12 UTC, mereolog commented on VS/VehicleSignals.rdf
> +		<rdfs:label xml:lang="en">Sonar</rdfs:label>
Note that https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#naming-and-labeling-conventions requires all labels be lower case.

2023-01-09 09:12 UTC, mereolog commented on VS/VehicleSignals.rdf
> +		<rdfs:label xml:lang="en">Throttle actuator</rdfs:label>
Note that https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#naming-and-labeling-conventions requires all labels be lower case.

2023-01-09 09:12 UTC, mereolog commented on VS/VehicleSignals.rdf
> +		<rdfs:label xml:lang="en">Voltage sensor</rdfs:label>
Note that https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#naming-and-labeling-conventions requires all labels be lower case.

2023-01-10 17:13 UTC, mereolog approved these changes

2023-01-10 17:13 UTC, mskulim approved these changes

2023-01-10 17:23 UTC, merged