Missing definitions added (WIP)
edmcouncil/auto pull request #84
Opened 2022-07-27 11:26 UTC by mereolog

Signed-off-by: mereolog <pawel.garbacz@makolab.com>

Fixes: #83

2022-08-01 20:39 UTC, mskulim requested changes
1) There are still classes and properties without definitions. 
2) The names of several properties aren't expressed in lower camel case.

2022-08-01 20:39 UTC, mskulim commented on DE/TrafficIncidents.rdf
> +		<skos:definition xml:lang="en">all road accidents - irrespective of whether there is an accident or serious material damage</skos:definition>
This definition seems unclear. Traffic incident defined as all road accidents?

2022-08-03 09:50 UTC, mereolog commented
> * There are still classes and properties without definitions.
We will deal with them at a later point.
> * The names of several properties aren't expressed in lower camel case.
This should raised as a separate issue and fixed in a different pull request.

2022-08-03 09:52 UTC, mereolog commented on DE/TrafficEnvironment.rdf
>  	</owl:Class>
> Class names must be singular.

This should raised as a separate issue and fixed in a different pull request.

2022-08-03 10:09 UTC, mereolog commented on DE/CarControl.rdf
> +		<skos:definition xml:lang="en">relates a vehicle to an intersection it is approaching</skos:definition>
> A vehicle can approach not only an intersection, but, for example, another vehicle. Is this definition correct?

This definition was taken from https://www.researchgate.net/publication/318079353_Ontology-Based_Driving_Decision_Making_A_Feasibility_Study_at_Uncontrolled_Intersections, which is the original source of this property.

2022-08-03 10:26 UTC, mereolog commented on VC/VehicleCore.rdf
> +		<skos:definition xml:lang="pl">pojazd samochodowy zaopatrzony w silnik spalinowy, dwukołowy lub z bocznym wózkiem – wielośladowy</skos:definition>
> Does this class not include electric motorcycles? That's according to the definition in Polish.

This definition was not added in this pull request, so it deserves a separate issue and another pull request.

2022-08-04 20:52 UTC, mskulim approved these changes

2022-08-05 12:45 UTC, merged