Logical descriptions for new classes added (WIP)
edmcouncil/auto pull request #89
Opened 2022-08-31 07:57 UTC by mereolog

Signed-off-by: mereolog <pawel.garbacz@makolab.com>

Fixes: #88

2022-09-01 22:06 UTC, mskulim requested changes

2022-09-01 22:06 UTC, mskulim commented on VC/VehicleParts.rdf
> +		<owl:annotatedSource rdf:resource="&auto-vp;ExternalLights"/>
This name is not singular.

2022-09-02 06:28 UTC, mereolog commented on VC/VehicleParts.rdf
> +		<rdfs:subClassOf rdf:resource="&auto-vp;Mirrors"/>
This will be addressed in a later PR.

2022-09-02 06:28 UTC, mereolog commented on VC/VehicleParts.rdf
> +		<owl:annotatedSource rdf:resource="&auto-vp;ExternalLights"/>
This will be addressed in a later PR.

2022-09-02 08:13 UTC, mskulim approved these changes

2022-09-02 14:29 UTC, merged